public with sharing class testforSublime {
/*
    private final sobject mysobject;

    // the extension constructor initializes the private member
    // variable mysobject by using the getrecord method from the standard
    // controller.
    public testforsublime(apexpages.standardcontroller stdcontroller) {
        this.mysobject = (sobject)stdcontroller.getrecord();
    }

    public string getrecordname() {
        return 'hello ' + (string)mysobject.get('name') + ' (' + (id)mysobject.get('id') + ')';
    }*/
    
}