@isTest
public class TestClassForCreatingContact {

    static testMethod void createContact(){
     /*   
        Test.startTest();
        Account accObj=new Account(Name='aBa');
        insert(accObj);
        Contact conObj= new Contact(LastName='mani',AccountId=accObj.Id);
        insert(conObj);      
        
        Test.stopTest();
   */ }
    static testMethod void updateContact(){
     /*   
        
        Test.startTest();
        Account accObj=new Account(Name='sample');
        insert(accObj);
        
        Contact conObj= new Contact();
        conObj.LastName='man';
        conObj.AccountId=accObj.Id;
        insert(conObj);   
        
        
        accObj.Name='testsample';
        update(accObj);
        
        conObj.LastName=conObj.LastName+ ' ' + accObj.Name;
        update(conObj);
        
        Test.stopTest();
    */}
    
   
    
}